"""empty message

Revision ID: 5b4ea1a3c1b8
Revises: d5e8672c39a8
Create Date: 2021-01-03 02:29:32.293854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b4ea1a3c1b8'
down_revision = 'd5e8672c39a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'blog', ['blog_id'], ['id'])
    op.drop_column('comment', 'question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_2', 'comment', 'blog', ['question_id'], ['id'])
    op.drop_column('comment', 'blog_id')
    # ### end Alembic commands ###
