"""empty message

Revision ID: ae801b7190c7
Revises: d89a64e48f60
Create Date: 2021-01-03 01:04:25.080747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae801b7190c7'
down_revision = 'd89a64e48f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('blog', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.alter_column('blog', 'content',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.create_foreign_key(None, 'blog', 'user', ['author_id'], ['id'])
    op.drop_column('blog', 'current_user')
    op.drop_column('blog', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('date_created', mysql.DATETIME(), nullable=True))
    op.add_column('blog', sa.Column('current_user', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.alter_column('blog', 'content',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    op.drop_column('blog', 'create_time')
    op.drop_column('blog', 'author_id')
    # ### end Alembic commands ###
